### ISSUE TITLE
Reversed Speaker Audio Output?

### ISSUE THREAD

**Issue by Swagsy** [reiryuki/Mi-Sound-Redmi-K40-Magisk-Module#7]
I'm on the Poco F3, CrDroid Android 13 and with Bluetooth Headphones, Dolby works perfect, but when enabled for speakers, it feels like the audio channels/speaker outputs are inverted. Usually the bassy sound comes out from the bottom speakers and the higher frequencies from the ones on the top on stock F3 MIUI Dolby. On the port it sounds reversed, is that possibly fixable?

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author. Also read #global_optionals also.
